version: "3.8"
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
      RABBITMQ_DEFAULT_VHOST:
#    ports:
#      - 5672:5672
#      - 15672:15672
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - rabbitmq
#     volumes:
#      - ./DucatusXAA/exchanges:/code/DucatusXAA/exchanges
#      - ./DucatusXAA/rates:/code/DucatusXAA/rates
#      - ./DucatusXAA/transfers:/code/DucatusXAA/transfers
#      - ./DucatusXAA/withdrawals:/code/DucatusXAA/withdrawals
