filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.and:
        - equals:
            container.labels.com_docker_compose_project: gold_crowdsale_backend
        - contains:
              container.image.name: docker.elastic.co
    - index: "filebeat-apps-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        container.labels.com_docker_compose_project: gold_crowdsale_backend

logging.json: true
logging.metrics.enabled: false
